/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeongenerator;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Jake
 */
public class DungeonDisplayPanel extends javax.swing.JPanel {

    
    public Dungeon dungeon;
    
    /**
     * Creates new form DungeonDisplayPanel
     */
    public DungeonDisplayPanel(Dungeon dng) {
        initComponents();
        dungeon = dng;
        this.setPreferredSize(new java.awt.Dimension(1+dng.getWidth()*5, 1+dng.getHeight()*5));
        this.setMinimumSize(new java.awt.Dimension(1+dng.getWidth()*5, 1+dng.getHeight()*5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    Color[] colors = new Color[10000];
    
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.setColor(Color.black);
        g.fillRect(0, 0, dungeon.getWidth()*5+1, dungeon.getHeight()*5+1);
        for(int i = 0; i<dungeon.getWidth(); i++)
            for(int j = 0; j<dungeon.getHeight(); j++)
            {
                if(dungeon.get(i,j))
                {
                    //g.setColor(clrs[dungeon.getZone(i, j)%8]);
                    if(colors[dungeon.getZone(i, j)]==null)
                    {
                        Random rng = new Random(dungeon.getZone(i, j));
                        colors[dungeon.getZone(i, j)] = new Color(rng.nextInt(200)+55,rng.nextInt(200)+55,rng.nextInt(200)+55);
                    }
                    g.setColor(colors[dungeon.getZone(i, j)]);
                    g.fillRect(1+5*i, 1+5*j, 4, 4);
                }
            }
    }
    
}
